language: objective-c
cache: cocoapods
osx_image: xcode7.3

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Swiftcraft.xcworkspace -scheme Swiftcraft-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
