language: objective-c
cache: cocoapods
osx_image: xcode7.3

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/Swiftcraft.xcworkspace -scheme Swiftcraft-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

notifications:
  slack:
    secure: NzDO+p+so3DhKDRSRV+VGVsTavcGH23v8WsdHHCUXF+viWVLqs8IbrHIpXJb9/FFUvrMffdJ1HF3Bcg45p5sLUY3YitQsZqyr4Sk21PsTUqElzpN2eONE6zmSceFAooFDMaQF3rxVbfqikdmYSyuM6P8ZExUAnBfHWmLqPLgsKoWUA3t5vaJBPxftFuSS9t+0fFVAyVS3U7EuRWPZLRD0FFzpbjltmouQ49VfVXHZ4ZoEEpcWgUYnsWbQuLAVkAOyOuxo4a5HiZuckV7WZQeALbYmFLJENpKeyIve1T/kuf7WdfNUFosRWXyV+KlcbgBp7s2mz0l4pVuvzHrAqB6xmsM+bbBiDaKyicxzE1vRCSa5b1wh0vGx+ndF3A5DKKSptPtxdL85VfSpIgboIeAncY/3abw67Wrc8trho6DVlsseG/SeXiKpOZsQ+PboiqDc26TnxefKv25wzTRigb40ePptjcXkOtjcKa9yj3PabAHYr0OHSOm3Gr5TdjIkT3p9QuyeSSdIu0b8/X4Q4UwAlsG6uPv/flQr2bDj5nYnK1DI9PYPe+E6vPyXLBsrKHSy7SLfIQ8nNxoqtZk2xY0k5nBjZ+6lv8h2ZeJc23jchLmaGYtx3OM7u5Cv2c5diXKHtwLOD3xJ5fAjD4cCRodVoaEWy5U09gQjeARLPDkFS8=
